### ISSUE TITLE
Autoplay active on invisible screen

### ISSUE THREAD

**Issue by frediustcDev** [serenader2014/flutter_carousel_slider#201]
Performance issue: 
The autoplay keeps playing while the screen is not the top most screen causing the onpagechanged function to be executed again and again

**Comment by serenader2014** [comment]
Sorry for taking so long to fix this problem, it was fixed in the v2.3.0 version, please have a try.

**Comment by rehamalraee** [comment]
@frediustcDev  hello! is it fixed within your code? I'm using v2.3.1 and it is not fixed!
